using HRM.Application.Common.Interfaces.Services;
using HRM.Application.Extensions;
using HRM.Application.Features.Employees.Dtos;
using QuestPDF.Fluent;
using QuestPDF.Helpers;

namespace HRM.Application.Common.Services;

public class EmployeeService : IEmployeeService
{
    public byte[] GenerateDynamicReport(List<EmployeeReportDto> employees, List<string> selectedFields)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4.Portrait());
                page.Margin(30);
                page.DefaultTextStyle(x => x.FontSize(12));
                page.Header().Text("Employee Report").SemiBold().FontSize(22).FontColor(Colors.Blue.Medium);

                page.Content().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        for (int i = 0; i < selectedFields.Count; i++)
                            columns.RelativeColumn();
                    });

                    // Header
                    table.Header(header =>
                    {
                        foreach (var field in selectedFields)
                            header.Cell().Element(CellStyleExtensions.CellStyle).Text(field).SemiBold();
                    });

                    // Rows
                    foreach (var emp in employees)
                    {
                        foreach (var field in selectedFields)
                        {
                            var prop = emp.GetType().GetProperty(field);
                            var value = prop?.GetValue(emp, null)?.ToString() ?? "-";
                            table.Cell().Element(CellStyleExtensions.CellStyle).Text(value);
                        }
                    }
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by HRMSample System ");
                    x.Span(DateTime.Now.ToString("yyyy/MM/dd HH:mm"));
                });
            });
        });

        return document.GeneratePdf();
    }
}
